//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ClientLibrary
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class testEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new testEntities object using the connection string found in the 'testEntities' section of the application configuration file.
        /// </summary>
        public testEntities() : base("name=testEntities", "testEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new testEntities object.
        /// </summary>
        public testEntities(string connectionString) : base(connectionString, "testEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new testEntities object.
        /// </summary>
        public testEntities(EntityConnection connection) : base(connection, "testEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<adminuser> adminusers
        {
            get
            {
                if ((_adminusers == null))
                {
                    _adminusers = base.CreateObjectSet<adminuser>("adminusers");
                }
                return _adminusers;
            }
        }
        private ObjectSet<adminuser> _adminusers;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the adminusers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToadminusers(adminuser adminuser)
        {
            base.AddObject("adminusers", adminuser);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="testModel", Name="adminuser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class adminuser : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new adminuser object.
        /// </summary>
        /// <param name="adminUserID">Initial value of the AdminUserID property.</param>
        public static adminuser Createadminuser(global::System.Int32 adminUserID)
        {
            adminuser adminuser = new adminuser();
            adminuser.AdminUserID = adminUserID;
            return adminuser;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AdminUserID
        {
            get
            {
                return _AdminUserID;
            }
            set
            {
                if (_AdminUserID != value)
                {
                    OnAdminUserIDChanging(value);
                    ReportPropertyChanging("AdminUserID");
                    _AdminUserID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AdminUserID");
                    OnAdminUserIDChanged();
                }
            }
        }
        private global::System.Int32 _AdminUserID;
        partial void OnAdminUserIDChanging(global::System.Int32 value);
        partial void OnAdminUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    
    }

    #endregion

    
}
